### ISSUE TITLE
Trying to deploy exporter to CF and getting this error

### ISSUE THREAD

**Issue by omearaj** [cloudfoundry-community/bosh_exporter#6]
2016-11-28T12:58:23.26-0700 [APP/0]      ERR time="2016-11-28T19:58:23Z" level=error msg="Error reading BOSH Info: Fetching info: Performing request GET 'https://10.193.51.131:25555/info': Performing GET request: Get https://10.193.51.131:25555/info: x509: cannot validate certificate for 10.193.51.131 because it doesn't contain any IP SANs" source="bosh_exporter.go:230"

I believe I have properly configured the app with the correct env variables.
- BOSH_EXPORTER_BOSH_URL
- BOSH_EXPORTER_BOSH_USERNAME
- BOSH_EXPORTER_BOSH_PASSWORD
- BOSH_EXPORTER_BOSH_CA_CERT_FILE

Thanks

**Comment by frodenas** [comment]
Jaimie, are you deploying the exporter as a CF app? Maybe it's the CA Cert file location? I was able to push the exporter to my `pcfdev` using the following manifest:

```yaml
---
applications:
  - name: bosh-exporter
    buildpack: go_buildpack
    env:
      BOSH_EXPORTER_BOSH_URL: "https://192.168.50.4:25555"
      BOSH_EXPORTER_BOSH_USERNAME: "admin"
      BOSH_EXPORTER_BOSH_PASSWORD: "admin"
      BOSH_EXPORTER_BOSH_CA_CERT_FILE: "bosh-lite-ca.crt"
``` 

Otherwise, it might be the CA Cert file not containing the SAN with the IP address of the BOSH Director. Please check this section of the FAQ that explains "[how can you get the BOSH CA certificate?](https://github.com/cloudfoundry-community/bosh_exporter/blob/master/FAQ.md#how-can-i-get-the-bosh-ca-certificate)".
