### ISSUE TITLE
bosh director uaa certificate doesn't contain any IP SANs

### ISSUE THREAD

**Issue by avasseur-pivotal** [cloudfoundry-community/bosh_exporter#7]
Running this for a PCF 1.9 I have this error showing up.
(192.168.0.1 is my bosh director)

The director was created by PCF OpsManager 1.9.1 = bosh-ini - how can I explore for its certificate ?
```
bosh-init --version
version 0.0.99-1c660f1-2016-11-11T23:51:52Z
```

Is there a way to configure bosh_exporter to ignore ssl cert verification - I am not too sure how OpsMan can generate the right bosh director cert with an IP SAN.

```
 - name: bosh_exporter
    release: prometheus
    properties:
      bosh_exporter:
        bosh:
          uaa:
            url: ((bosh_exporter.bosh.uaa.url))
            client_id: ((bosh_exporter.bosh.uaa.client_id))
            client_secret: ((bosh_exporter.bosh.uaa.client_secret))
          url: ((bosh_exporter.bosh.url))
          ca_cert: ((bosh_exporter.bosh.ca_cert))
          collectors: Deployments,Jobs,ServiceDiscovery
```

```
time="2017-02-02T17:21:49Z" level=info msg="Starting bosh_exporter (version=2.1.3, branch=master, revision=6fae8f253d6d6e41aaf65bbc61a2b8f49e33f524)" source="bosh_exporter.go:219"
time="2017-02-02T17:21:49Z" level=info msg="Build context (go=go1.7.4, user=root@3ef3729f9e16, date=20170119-23:06:08)" source="bosh_exporter.go:220"
time="2017-02-02T17:21:49Z" level=error msg="Error reading BOSH Info: Fetching info: Performing request GET 'https://192.168.0.1:25555/info': Performing GET request: Requesting token via client credentials grant: Performing request POST 'https://192.168.0.1:8443/oauth/token?grant_type=client_credentials': Performing POST request: Post https://192.168.0.1:8443/oauth/token?grant_type=client_credentials: x509: cannot validate certificate for 192.168.0.1 because it doesn't contain any IP SANs" source="bosh_exporter.go:230"
```
